command:
  - "python"
  - "app.py"

env:
  - name: USE_MOCK_BACKEND
    value: "false"
  - name: DATABRICKS_WAREHOUSE_ID
    value: "d24059778e957e41"
  - name: DATABRICKS_CATALOG
    value: "cme_outcomes_uswest"
  - name: DATABRICKS_SCHEMA
    value: "media_demo"
